version: '3.7'
services:
  db:
    image: postgres:11
    restart: always
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: divise