addSbtPlugin("org.scalameta"     % "sbt-scalafmt"         % "2.0.2")
addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph" % "0.9.2")
addSbtPlugin("com.typesafe.play" % "sbt-plugin"           % "2.7.3")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager"  % "1.2.1")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"         % "0.14.6")
addSbtPlugin("com.typesafe.sbt"  % "sbt-twirl"            % "1.4.2")
