CREATE TABLE SCHEDULE
(
    ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR NOT NULL
);

CREATE TABLE CONTACT
(
    ID BIGSERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR NOT NULL,
    LAST_NAME  VARCHAR NOT NULL,
    EMAIL      VARCHAR,
    PHONE      VARCHAR,
    TG_ID      VARCHAR,
    VIBER_ID   VARCHAR
);

CREATE TABLE EVENT
(
    ID BIGSERIAL PRIMARY KEY,
    SCHEDULE_ID  BIGINT NOT NULL REFERENCES SCHEDULE,
    CONTACT_ID  BIGINT   NOT NULL REFERENCES CONTACT,
    DATE  DATE  NOT NULL,
    START_TIME  TIME NOT NULL,
    END_TIME    TIME NOT NULL,
    IS_OCCUPIED BOOLEAN  NOT NULL DEFAULT FALSE
);


